version: '3'

services:

  wordpress:
    depends_on:
      - db
    image: wordpress:php7.2
    ports:
      - '8000:80'
    restart: always
    volumes: ['./wp_site:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    # network_mode: bridge

  db:
    image: mysql:8.0
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress 
    # network_mode: bridge
    
  phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - '8080:80'
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: password 


volumes:
  db_data:
  wp_site:
# networks:
#   default: